Vet clinic database: query and update animals table
HENRYKC24/vet-clinic-database pull request #2
Opened 2021-10-26 22:25 UTC by HENRYKC24

In this pull request, I:
1. Added a column species of type string to my animals' table.
2. Inserted the following data:
Animal: His name is Charmander. He was born on Feb 8th, 2020, and currently weighs -11kg. He is not neutered and he has never tried to escape.
Animal: Her name is Plantmon. She was born on Nov 15th, 2022, and currently weighs -5.7kg. She is neutered and she has tried to escape 2 times.
Animal: His name is Squirtle. He was born on Apr 2nd, 1993, and currently weighs -12.13kg. He was not neutered and he has tried to 3 times.
Animal: His name is Angemon. He was born on Jun 12th, 2005, and currently weighs -45kg. He is neutered and he has tried to escape once.
Animal: His name is Boarmon. He was born on Jun 7th, 2005, and currently weighs 20.4kg. He is neutered and he has tried to escape 7 times.
Animal: Her name is Blossom. She was born on Oct 13th, 1998, and currently weighs 17kg. She is neutered and she has tried to escape 3 times.
3. Updated the animals' table Inside a transaction by setting the species column to unspecified. Verified that change was made. Then rolled back the change and verified that species columns went back to the state before the transaction.
4. Inside a transaction:
Updated the animals' table by setting the species column to Digimon for all animals that have a name ending with mon.
Updated the animals' table by setting the species column to pokemon for all animals that don't have species already set.
Committed the transaction.
Verified that change was made and persists after commit.
5. Inside a transaction:
Deleted all animals born after Jan 1st, 2022.
Created a savepoint for the transaction.
Updated all animals' weight to be their weight multiplied by -1.
Rolled back to the savepoint
Updated all animals' weights that are negative to be their weight multiplied by -1.
Committed transaction
6. Wrote queries to answer the following questions:
How many animals are there?
How many animals have never tried to escape?
What is the average weight of animals?
Who escapes the most, neutered or not neutered animals?
What is the minimum and maximum weight of each type of animal?
What is the average number of escape attempts per animal type of those born between 1990 and 2000?

2021-10-26 22:50 UTC, sinansevgi requested changes
# Changes Required :recycle: 
------

Hi @HENRYKC24, 

Good job so far!
Most of the queries looks good :+1: 
There are some issues that you still need to work on to go further but you are almost there!


 ## Required Changes ♻️
_Please check the inline comments for my suggestions_ :arrow_down:

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Happy Hacking! :computer: 

-----

You can reply to this conversation if you have any questions or need elaboration. :wave: 
Sinan Sevgi

------

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-10-26 22:50 UTC, sinansevgi commented on queries.sql
> +
- [ ] You should verify the changes successfully rollbacked.

> Inside a transaction update the animals table by setting the species column to unspecified. Verify that change was made. Then roll back the change and **verify that species columns went back to the state before transaction**.

```suggestion
BEGIN;
UPDATE animals SET species='unspecified';
SELECT * FROM animals;
ROLLBACK;
SELECT species from animals; -- verify that change was undone


```

2021-10-26 22:50 UTC, sinansevgi commented on queries.sql
> +UPDATE animals SET species='pigimon' WHERE name LIKE '%mon';
- [ ] The name of the species should be digimon :smile: 
```suggestion
UPDATE animals SET species='digimon' WHERE name LIKE '%mon';
```

2021-10-26 22:50 UTC, sinansevgi commented on queries.sql
> +SELECT SUM(weight_kg) / count(*) AS average_weight FROM animals;
[Optional]
- [ ] SQL has the AVG function to easily calculate the average value. 
```suggestion
   SELECT AVG(weight_kg) FROM animals;
```

2021-10-26 22:50 UTC, sinansevgi commented on queries.sql
> +);
[Optional]
- [ ] Again SQL's AVG function can help you in these situations.
```suggestion
   SELECT neutered, AVG(escape_attempts) FROM animals
   GROUP BY neutered;
```

2021-10-26 23:07 UTC, HENRYKC24 commented on queries.sql
> +
Thank you for pointing that out. I greatly appreciate it.

2021-10-26 23:10 UTC, HENRYKC24 commented on queries.sql
> +UPDATE animals SET species='pigimon' WHERE name LIKE '%mon';
Oh! :smile:
Thank you.

2021-10-26 23:12 UTC, HENRYKC24 commented on queries.sql
> +SELECT SUM(weight_kg) / count(*) AS average_weight FROM animals;
Thank you.

2021-10-26 23:32 UTC, HENRYKC24 commented on queries.sql
> +);
The question I want to answer here is:
Who escapes the most, neutered or not neutered animals?
I think that the answer to this question is finding which animals escape the most. Is it the neutered or not neutered animals? I summed the escape attempts for the neutered and also for the not neutered. Finally, I checked which between them had the maximum number of escape attempts. I think I needed to return either neutered or not neutered and that is what I did.
Please, check this:point_down:
![image](https://user-images.githubusercontent.com/45668340/138975017-01477091-916b-426e-8bc7-723eaacfc9f5.png)
If you check the total escape attempts for all the neutered animals it gives 18 escape attempts, which is more than that of the not neutered (4 escape attempts).
What do you think?:thinking:

2021-10-26 23:45 UTC, sinansevgi commented on queries.sql
> +);
What you're doing is right, and it might be better if you're doing data analysis.  I just wanted you to know that you can find it easily as I suggested.  That's why I marked it as optional.  The group that escapes the most will always have the higher average escape.

2021-10-27 00:16 UTC, peterrobert commented on queries.sql
> +
This change has been made succesfully

2021-10-27 00:17 UTC, peterrobert commented on queries.sql
> +UPDATE animals SET species='pigimon' WHERE name LIKE '%mon';
This change has been made succesfully

2021-10-27 00:19 UTC, peterrobert commented on queries.sql
> +SELECT SUM(weight_kg) / count(*) AS average_weight FROM animals;
This optional change has been done successfully

2021-10-27 00:19 UTC, HENRYKC24 commented on queries.sql
> +);
I think you are right but I also imagined another scenario where specie A has 3 records with 20 escape attempts each. Then, specie B has 4 records with three of them having same escape attempts as that of A (20 each). 

If the fourth has escape attempts of 2 for example, the total escape attempts for specie B would be greater but it's average will, at the same time, be less than that of A. Please, does it make sense?

Though I had submitted another pull request for a re-review before I received your last comment, I would consider using your approach still later.

2021-10-27 00:22 UTC, peterrobert approved these changes
Hi @HENRYKC24 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-10-27 06:41 UTC, HENRYKC24 commented
Thank you, @peterrobert  and @sinansevgi, for all your efforts in making my project better. I greatly appreciate that.

2021-10-27 06:41 UTC, merged